### ISSUE TITLE
Brew install not working

### ISSUE THREAD

**Issue by berkaytheunicorn** [jimmymasaru/fp-gen#1]
Hey there, I just tried to install the package from brew on macOS 10.14.5 but somehow it
either won't install or  won't expose fpgen.

**Comment by jimmymasaru** [comment]
Thank you for reporting this. There was an issue in the brew formula file and it has been fixed.
Please try those commands to install: `brew install fp-gen` or `brew install jimmymasaru/repo/fp-gen`
